[context.branch-deploy.environment]
ANGULAR_FIREBASE_API_KEY= "AIzaSyCWMnafh3AOD7qg3ky0c-yC8UF6coPGhyA"
ANGULAR_FIREBASE_AUTH_DOMAIN= "white-rabbit-dev.firebaseapp.com"
ANGULAR_FIREBASE_PROJECT_ID= "white-rabbit-dev"
ANGULAR_FIREBASE_STORAGE_BUCKET= "white-rabbit-dev.appspot.com"
ANGULAR_FIREBASE_MESSAGING_SENDER_ID= "909829576199"
ANGULAR_FIREBASE_APP_ID= "1:909829576199:web:ff76c70601b675c2e0bca2"
ANGULAR_GOOGLE_MAPS_API_KEY= "AIzaSyA25_4wdIbQddm3Yxj7nhnsQgg1VSyCHyI"
